In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import pandas as pd
import re
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /Users/danylo/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]

[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /Users/danylo/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_dat

[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to
[nltk_data]    |     /Users/danylo/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[n

True

In [2]:
data = pd.read_csv('/Users/danylo/Downloads/IMDB Dataset.csv')
print(data.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [3]:
data.duplicated().value_counts()

False    49582
True       418
dtype: int64

In [4]:
data.drop_duplicates(inplace=True)
data.duplicated().value_counts()

False    49582
dtype: int64

In [5]:
def cleaning_step_1(text):
    url = re.compile(r'https://\S+|www\.\S+')
    text = url.sub(r'', text)
    html = re.compile(r'<.*?>')
    text = html.sub(r'', text)
    punctuation = re.compile(r'[^\w\s]')
    text = punctuation.sub(r'', text)
    special_char = re.compile(r'[^a-zA-Z0-9\s]')
    text = special_char.sub(r'', text)
    emojis = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)
    text = emojis.sub(r'', text)
    text = text.lower()
    return text

In [6]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [7]:
data['review'] = data['review'].apply(cleaning_step_1)
data['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production the filming tech...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: review, dtype: object

In [11]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
def preprocessing_step_2(text):
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(text)
    filtered_sentence = []
    for w in word_tokens:
        if w not in stop_words:
            filtered_sentence.append(w)
    ps = PorterStemmer()
    for word in filtered_sentence:
        word = ps.stem(word)
    lemmatizer = WordNetLemmatizer()
    for word in filtered_sentence:
        word = lemmatizer.lemmatize(word)
    final_string = ""
    for word in filtered_sentence:
        final_string = final_string + word + " "
    return final_string

In [12]:
data['review'] = data['review'].apply(preprocessing_step_2)

In [13]:
data['sentiment'].replace({'negative' : 0, 'positive' : 1}, inplace=True)
data

review  sentiment
0      one reviewers mentioned watching 1 oz episode ...          1
1      wonderful little production filming technique ...          1
2      thought wonderful way spend time hot summer we...          1
3      basically theres family little boy jake thinks...          0
4      petter matteis love time money visually stunni...          1
...                                                  ...        ...
49995  thought movie right good job wasnt creative or...          1
49996  bad plot bad dialogue bad acting idiotic direc...          0
49997  catholic taught parochial elementary schools n...          0
49998  im going disagree previous comment side maltin...          0
49999  one expects star trek movies high art fans exp...          0

[49582 rows x 2 columns]

In [14]:
reviews = data['review']
reviews

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically theres family little boy jake thinks...
4        petter matteis love time money visually stunni...
                               ...                        
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 49582, dtype: object

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 10000)
x = cv.fit_transform(data['review']).toarray()
y = data['sentiment']
x.shape

(49582, 10000)

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [17]:
x_train.shape

(39665, 10000)

In [18]:
x_test.shape

(9917, 10000)

In [19]:
y_train.shape

(39665,)

In [20]:
y_test.shape

(9917,)

In [21]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
model1 = GaussianNB()
model2 = MultinomialNB()
model3 = BernoulliNB()
                              
model1.fit(x_train, y_train)

GaussianNB()

In [22]:
model2.fit(x_train, y_train)

MultinomialNB()

In [23]:
model3.fit(x_train, y_train)

BernoulliNB()

In [24]:
GaussianNB_pred = model1.predict(x_test)  
MultinomialNB_pred = model2.predict(x_test)  
BernoulliNB_pred = model3.predict(x_test)  

  
GaussianNB_pred

array([0, 0, 0, ..., 0, 0, 1])

In [25]:
from sklearn.metrics import confusion_matrix
  
confusion_matrix1 = confusion_matrix(y_test, GaussianNB_pred)  
  
confusion_matrix1 

array([[4178,  719],
       [1948, 3072]])

In [26]:
confusion_matrix2 = confusion_matrix(y_test, MultinomialNB_pred)  

confusion_matrix2 

array([[4199,  698],
       [ 808, 4212]])

In [27]:
confusion_matrix3 = confusion_matrix(y_test, BernoulliNB_pred)  

confusion_matrix3 

array([[4219,  678],
       [ 782, 4238]])

In [28]:
#part 2

In [29]:
movies = pd.read_csv('/Users/danylo/Downloads/ml-25m/movies.csv')
movies

movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
62418   209157                           We (2018)   
62419   209159           Window of the Soul (2001)   
62420   209163                    Bad Poems (2018)   
62421   209169                 A Girl Thing (2001)   
62422   209171      Women of Devil's Island (1962)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
62418                                        Drama  
62419                                  Documentary  
62420                                 Comedy|Drama  
62421                           (no genres listed)  
62422                       Action|Adventure|Drama  

[62423 rows x 3 columns]

In [30]:
def clean(string):
    string = re.sub("[^a-zA-Z0-9 ]", "", string)
    return string

movies["title"] = movies["title"].apply(clean)
movies

movieId                             title  \
0            1                    Toy Story 1995   
1            2                      Jumanji 1995   
2            3             Grumpier Old Men 1995   
3            4            Waiting to Exhale 1995   
4            5  Father of the Bride Part II 1995   
...        ...                               ...   
62418   209157                           We 2018   
62419   209159           Window of the Soul 2001   
62420   209163                    Bad Poems 2018   
62421   209169                 A Girl Thing 2001   
62422   209171       Women of Devils Island 1962   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
62418                                        Drama  
62419                                  Documentary  
62420                                 Comedy|Drama  
62421                           (no genres listed)  
62422                       Action|Adventure|Drama  

[62423 rows x 3 columns]

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2))

tfidf = vectorizer.fit_transform(movies["title"])

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

def search(string):
    title = clean(string)
    query_vec = vectorizer.transform([string])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    results = movies.iloc[indices].iloc[::-1]

    return results

In [33]:
search('spiderman')

movieId                         title  \
5241      5349                SpiderMan 2002   
18241    95510    Amazing SpiderMan The 2012   
11561    52722              SpiderMan 3 2007   
7923      8636              SpiderMan 2 2004   
21454   110553  The Amazing SpiderMan 2 2014   

                                      genres  
5241        Action|Adventure|Sci-Fi|Thriller  
18241           Action|Adventure|Sci-Fi|IMAX  
11561  Action|Adventure|Sci-Fi|Thriller|IMAX  
7923            Action|Adventure|Sci-Fi|IMAX  
21454                     Action|Sci-Fi|IMAX

In [34]:
movie = movies[movies["movieId"] == movie_id]

NameError: name 'movie_id' is not defined

In [35]:
ratings = pd.read_csv('/Users/danylo/Downloads/ml-25m/ratings.csv')
ratings.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [36]:
def find_similar_movies(movie_id, sentiment):
    if (sentiment == 1):
        similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] > 4)]["userId"].unique()
    if (sentiment == 0):
        similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] < 2)]["userId"].unique()
        
    similar_user_recs = ratings[(ratings["userId"].isin(similar_users)) & (ratings["rating"] > 4)]["movieId"]
    similar_user_recs = similar_user_recs.value_counts() / len(similar_users)
    similar_user_recs = similar_user_recs[similar_user_recs > .10]
    all_users = ratings[(ratings["movieId"].isin(similar_user_recs.index)) & (ratings["rating"] > 4)]
    all_user_recs = all_users["movieId"].value_counts() / len(all_users["userId"].unique())
    rec_percentages = pd.concat([similar_user_recs, all_user_recs], axis=1)
    rec_percentages.columns = ["similar", "all"]
    
    rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
    rec_percentages = rec_percentages.sort_values("score", ascending=False)
    return rec_percentages

In [37]:
find_similar_movies(3114, 0)

similar       all     score
2542  0.100105  0.053515  1.870615
1527  0.126449  0.068981  1.833091
4011  0.134879  0.075295  1.791339
4878  0.135933  0.077478  1.754471
1206  0.158061  0.090464  1.747217
...        ...       ...       ...
318   0.280295  0.356981  0.785182
593   0.179136  0.235653  0.760170
110   0.127503  0.167811  0.759799
356   0.177028  0.245413  0.721348
527   0.146470  0.224490  0.652458

[64 rows x 3 columns]

In [38]:
movie_name = input("Enter movie name: ")

Enter movie name: legally blonde


In [39]:
print(search(movie_name))
movieId = input("What is your movie's Id? ")

       movieId                                    title          genres
4342      4447                      Legally Blonde 2001  Comedy|Romance
6412      6535  Legally Blonde 2 Red White  Blonde 2003          Comedy
43153   165395          Legally Blonde The Musical 2007          Comedy
60887   204396                      Blonde Animals 2019    Comedy|Drama
19083    99444                          Blonde Ice 1948       Film-Noir
What is your movie's Id? 165395


In [40]:
review = input("What did you think of it? ")

What did you think of it? It's the best musical ever. laura bell is amazing and could sing very nice


In [41]:
review_apter_p1 = cleaning_step_1(review)
review_apter_p1

'its the best musical ever laura bell is amazing and could sing very nice'

In [42]:
review_apter_p2 = preprocessing_step_2(review_apter_p1)
list(review_apter_p2.split(" "))

['best',
 'musical',
 'ever',
 'laura',
 'bell',
 'amazing',
 'could',
 'sing',
 'nice',
 '']

In [43]:
final_vectorizer = CountVectorizer(vocabulary=cv.vocabulary_, lowercase=False)
final_x = final_vectorizer.fit_transform(review_apter_p2.split(" "))
print(final_x)


  (0, 973)	1
  (1, 5934)	1
  (2, 3175)	1
  (3, 5127)	1
  (4, 946)	1
  (5, 442)	1
  (6, 2102)	1
  (7, 8135)	1
  (8, 6057)	1


In [44]:
final_data = pd.DataFrame(final_x.todense())
final_data = final_data.sum()
print(final_data)

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Length: 10000, dtype: int64


In [45]:
final_array = []
final_array.append(final_data)
prediction = model3.predict(final_array)
prediction[0]

1

In [48]:
print(movieId)
find_similar_movies(int(movieId), int(prediction[0])).head(10).merge(movies, left_index=True, right_on="movieId")[["score", "title", "genres"]]

165395


score                                            title  \
49786  24500.333333                               Eat Play Love 2017   
41261  24500.333333                                Emmas Chance 2016   
40233  24500.333333               Annie Claus is Coming to Town 2011   
40230  24500.333333                           Strawberry Summer 2012   
43514  24500.333333  Von einem der auszog das Frchten zu lernen 2014   
43513  24500.333333           The Princess with the Golden Star 1959   
43512  24500.333333                                Aschenputtel 1989   
43510  24500.333333                              Schneewittchen 2009   
43508  24500.333333                                Aschenputtel 2011   
43507  24500.333333                     Die Schne und das Biest 2012   

                        genres  
49786           Comedy|Romance  
41261           Children|Drama  
40233  Children|Comedy|Romance  
40230                    Drama  
43514  Children|Fantasy|Horror  
43513         Children|Fantasy  
43512       (no genres listed)  
43510       (no genres listed)  
43508         Children|Fantasy  
43507         Children|Fantasy